import { Colleagues } from '../colleagues';

export const colleaguesList: Colleagues[] = [
    { id: 0, firstName: 'Armin', lastName: 'Otterstätter'},
    { id: 1, firstName: 'Christian', lastName: 'Löwe'},
    { id: 2, firstName: 'Dennis', lastName: 'Stanze'},
    { id: 3, firstName: 'Jerome', lastName: 'Goulet'},
    { id: 4, firstName: 'Kevin', lastName: 'Kremer'},
    { id: 5, firstName: 'Marian', lastName: 'Heck'},
    { id: 6, firstName: 'Mathieu', lastName: 'Weibel'},
    { id: 7, firstName: 'Maurice', lastName: 'Schlegel'},
    { id: 8, firstName: 'Max', lastName: 'Wölfel'},
    { id: 9, firstName: 'Michael', lastName: 'Glatt'},
    { id: 10, firstName: 'Michael', lastName: 'Maag'},
    { id: 11, firstName: 'Moritz', lastName: 'Schnaufer'},
    { id: 12, firstName: 'Muhammad', lastName: 'Abohegab'},
    { id: 13, firstName: 'Nazligül', lastName: 'Cayoglu'},
    { id: 14, firstName: 'Philipp', lastName: 'Andrikopoulos'},
    { id: 15, firstName: 'Richard', lastName: 'Montbrun'},
    { id: 16, firstName: 'Steffen', lastName: 'Rau'},
    { id: 17, firstName: 'Thomas', lastName: 'Renner'},
    { id: 18, firstName: 'Philipp', lastName: 'Andrikopoulos'},
    { id: 19, firstName: 'Philipp', lastName: 'Andrikopoulos'},
    { id: 20, firstName: 'Philipp', lastName: 'Andrikopoulos'},
    { id: 21, firstName: 'Philipp', lastName: 'Andrikopoulos'},
    { id: 22, firstName: 'Philipp', lastName: 'Andrikopoulos'},
    { id: 23, firstName: 'Philipp', lastName: 'Andrikopoulos'},
    { id: 24, firstName: 'Philipp', lastName: 'Andrikopoulos'},
    { id: 25, firstName: 'Philipp', lastName: 'Andrikopoulos'},
    { id: 26, firstName: 'Philipp', lastName: 'Andrikopoulos'}
]