import { Colleagues } from '../colleagues';

export const colleaguesList: Colleagues[] = [
    { id: 0, firstName: 'Armin', lastName: 'Otterstätter', imagePath: '../assets/images/mitarbeiter15.jpg'},
    { id: 1, firstName: 'Christian', lastName: 'Löwe', imagePath: '../assets/images/mitarbeiter5.jpg'},
    { id: 2, firstName: 'Dennis', lastName: 'Stanze', imagePath: '../assets/images/mitarbeiter7.jpg'},
    { id: 3, firstName: 'Jerome', lastName: 'Goulet', imagePath: '../assets/images/mitarbeiter11.jpg'},
    { id: 4, firstName: 'Kevin', lastName: 'Kremer', imagePath: '../assets/images/mitarbeiter8.jpg'},
    { id: 5, firstName: 'Marian', lastName: 'Heck', imagePath: '../assets/images/mitarbeiter13.jpg'},
    { id: 6, firstName: 'Mathieu', lastName: 'Weibel', imagePath: '../assets/images/mitarbeiter1.jpg'},
    { id: 7, firstName: 'Maurice', lastName: 'Schlegel', imagePath: '../assets/images/mitarbeiter1.jpg'},
    { id: 8, firstName: 'Max', lastName: 'Wölfel', imagePath: '../assets/images/mitarbeiter10.jpg'},
    { id: 9, firstName: 'Michael', lastName: 'Glatt', imagePath: '../assets/images/mitarbeiter2.jpg'},
    { id: 10, firstName: 'Michael', lastName: 'Maag', imagePath: '../assets/images/mitarbeiter3.jpg'},
    { id: 11, firstName: 'Moritz', lastName: 'Schnaufer', imagePath: '../assets/images/mitarbeiter12.jpg'},
    { id: 12, firstName: 'Muhammad', lastName: 'Abohegab', imagePath: '../assets/images/mitarbeiter9.jpg'},
    { id: 13, firstName: 'Nazligül', lastName: 'Cayoglu', imagePath: '../assets/images/mitarbeiter14.jpg'},
    { id: 14, firstName: 'Philipp', lastName: 'Andrikopoulos', imagePath: '../assets/images/mitarbeiter1.jpg'},
    { id: 15, firstName: 'Richard', lastName: 'Montbrun', imagePath: '../assets/images/mitarbeiter1.jpg'},
    { id: 16, firstName: 'Steffen', lastName: 'Rau', imagePath: '../assets/images/mitarbeiter6.jpg'},
    { id: 17, firstName: 'Thomas', lastName: 'Renner', imagePath: '../assets/images/mitarbeiter4.jpg'},
    { id: 18, firstName: 'Philipp', lastName: 'Andrikopoulos', imagePath: '../assets/images/mitarbeiter1.jpg'},
    { id: 19, firstName: 'Philipp', lastName: 'Andrikopoulos', imagePath: '../assets/images/mitarbeiter1.jpg'},
    { id: 20, firstName: 'Philipp', lastName: 'Andrikopoulos', imagePath: '../assets/images/mitarbeiter1.jpg'},
    { id: 21, firstName: 'Philipp', lastName: 'Andrikopoulos', imagePath: '../assets/images/mitarbeiter1.jpg'},
    { id: 22, firstName: 'Philipp', lastName: 'Andrikopoulos', imagePath: '../assets/images/mitarbeiter1.jpg'},
    { id: 23, firstName: 'Philipp', lastName: 'Andrikopoulos', imagePath: '../assets/images/mitarbeiter1.jpg'},
    { id: 24, firstName: 'Philipp', lastName: 'Andrikopoulos', imagePath: '../assets/images/mitarbeiter1.jpg'},
    { id: 25, firstName: 'Philipp', lastName: 'Andrikopoulos', imagePath: '../assets/images/mitarbeiter1.jpg'},
    { id: 26, firstName: 'Philipp', lastName: 'Andrikopoulos', imagePath: '../assets/images/mitarbeiter1.jpg'}
]